language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true


before_install:
  - pip freeze | xargs pip uninstall -y
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source "$HOME/.poetry/env"

install:
  - poetry install

script:
  - poetry run flake8 returns tests docs
  - poetry run mypy returns tests/**/*.py
  - poetry run pytest tests
  # Temporary work-around of
  # https://github.com/mkurnikov/pytest-mypy-plugins/issues/2
  - poetry run pytest -p no:cov -o addopts="" --mypy-ini-file=setup.cfg typesafety
  - poetry run doc8 -q docs
  - poetry check
  - poetry run pip check
  - poetry run safety check --bare --full-report

after_success:
  - pip install coveralls
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: change
